###

POST http://localhost:8080/api/category
Content-Type: application/json

{
     "categoryName": "Dining table"
}

###

PUT http://localhost:8080/api/category
Content-Type: application/json

{
     "categoryName": "Clothes-Test"
}


###

DELETE http://localhost:8080/api/category




###
GET  http://localhost:8080/api/category
Content-Type: application/json


###
GET  http://localhost:8080/api/category
Content-Type: application/json