###

POST http://localhost:8080/api/user
Content-Type: application/json

{
     "firstname": "Test",
     "lastname":"Test",
     "username":"test",
     "password":"wefwf",
     "email":"test"

}

###
POST http://localhost:8080/api/user/
Content-Type: application/json

{
     "firstname": "Amar",
     "lastname":"Hamar",
     "username" : "cringe",
     "password" : "qwe123",
     "email": "something@gmail.com"
}


###
GET http://localhost:8080/api/user?limit=10

###
GET http://localhost:8080/api/user/101

###
PUT http://localhost:8080/api/user/100
Content-Type: application/json

{
     "userName" : "Haliunaa"
}

 ###
GET http://localhost:8080/api/user/101